//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in as anonymous user.
        /// </summary>
        internal static string Button_SignInAnonym {
            get {
                return ResourceManager.GetString("Button_SignInAnonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Button_SignUp {
            get {
                return ResourceManager.GetString("Button_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start session.
        /// </summary>
        internal static string Button_StartSession {
            get {
                return ResourceManager.GetString("Button_StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop session.
        /// </summary>
        internal static string Button_StopSession {
            get {
                return ResourceManager.GetString("Button_StopSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;text-muted&quot;&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.&lt;/p&gt;&lt;p class=&quot;text-muted&quot;&gt;Lorem ipsum dolor sit ame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Content_About {
            get {
                return ResourceManager.GetString("Content_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2013 Andriy Babets.
        /// </summary>
        internal static string Content_Footer {
            get {
                return ResourceManager.GetString("Content_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Content_GeneralError {
            get {
                return ResourceManager.GetString("Content_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    jsDSTR is a javascript distributed system for clasterization big data. 
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    The main idea is to use browser as a processing node in calculations.
        ///    Processing are doing on the big array of geographic data.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string Content_Home {
            get {
                return ResourceManager.GetString("Content_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Content_PageWasNotFound {
            get {
                return ResourceManager.GetString("Content_PageWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click start button for beginning of calculation above. &lt;br /&gt;
        ///            You will become a little node in the great process. &lt;br /&gt;
        ///            Improve our world now!.
        /// </summary>
        internal static string Content_Processing {
            get {
                return ResourceManager.GetString("Content_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Content_ServerError {
            get {
                return ResourceManager.GetString("Content_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation queue is busy. Another attempt....
        /// </summary>
        internal static string Error_CalculationBusy {
            get {
                return ResourceManager.GetString("Error_CalculationBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation process is already completed. Thank you..
        /// </summary>
        internal static string Error_CalculationCompleted {
            get {
                return ResourceManager.GetString("Error_CalculationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation task returned error. Another attempt....
        /// </summary>
        internal static string Error_CalculationError {
            get {
                return ResourceManager.GetString("Error_CalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation process is failed. Please try again later..
        /// </summary>
        internal static string Error_CalculationFailed {
            get {
                return ResourceManager.GetString("Error_CalculationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation object is invalid. Another attempt....
        /// </summary>
        internal static string Error_CalculationInvalid {
            get {
                return ResourceManager.GetString("Error_CalculationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation task returned null. Another attempt....
        /// </summary>
        internal static string Error_CalculationNull {
            get {
                return ResourceManager.GetString("Error_CalculationNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel session error. Calculation was stopped..
        /// </summary>
        internal static string Error_CancelSession {
            get {
                return ResourceManager.GetString("Error_CancelSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete session error. Another attempt....
        /// </summary>
        internal static string Error_CompleteSession {
            get {
                return ResourceManager.GetString("Error_CompleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create session error. Another attempt....
        /// </summary>
        internal static string Error_CreateSession {
            get {
                return ResourceManager.GetString("Error_CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such email is already registered.
        /// </summary>
        internal static string Error_DuplicateEmail {
            get {
                return ResourceManager.GetString("Error_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        internal static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors occured. Please contact site administrator..
        /// </summary>
        internal static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation session was failed with max attempts count. Please try again later..
        /// </summary>
        internal static string Error_MaxAttemptsCalculateSession {
            get {
                return ResourceManager.GetString("Error_MaxAttemptsCalculateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating session was failed with max attempts count. Please try again later..
        /// </summary>
        internal static string Error_MaxAttemptsCreateSession {
            get {
                return ResourceManager.GetString("Error_MaxAttemptsCreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping session was failed with max attempts count. Please try again later..
        /// </summary>
        internal static string Error_MaxAttemptsPingSession {
            get {
                return ResourceManager.GetString("Error_MaxAttemptsPingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t accept terms.
        /// </summary>
        internal static string Error_NotAcceptedTerms {
            get {
                return ResourceManager.GetString("Error_NotAcceptedTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string Error_Password {
            get {
                return ResourceManager.GetString("Error_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping error. Another attempt....
        /// </summary>
        internal static string Error_PingSession {
            get {
                return ResourceManager.GetString("Error_PingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation was stopped with error. Another attempt....
        /// </summary>
        internal static string Error_SessionCalculation {
            get {
                return ResourceManager.GetString("Error_SessionCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client session is null.
        /// </summary>
        internal static string Error_SessionClientNull {
            get {
                return ResourceManager.GetString("Error_SessionClientNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned session with invalid state.
        /// </summary>
        internal static string Error_SessionInvalidState {
            get {
                return ResourceManager.GetString("Error_SessionInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned null session.
        /// </summary>
        internal static string Error_SessionServerNull {
            get {
                return ResourceManager.GetString("Error_SessionServerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        internal static string Error_SignIn {
            get {
                return ResourceManager.GetString("Error_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonym authorization error. Please contant administrator..
        /// </summary>
        internal static string Error_SignInAnonym {
            get {
                return ResourceManager.GetString("Error_SignInAnonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered.
        /// </summary>
        internal static string Error_SignUp {
            get {
                return ResourceManager.GetString("Error_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About jsDSTR.
        /// </summary>
        internal static string Header_About {
            get {
                return ResourceManager.GetString("Header_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string Header_GeneralError {
            get {
                return ResourceManager.GetString("Header_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About jsDSTR.
        /// </summary>
        internal static string Header_Home {
            get {
                return ResourceManager.GetString("Header_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - page wasn&apos;t found.
        /// </summary>
        internal static string Header_PageWasNotFound {
            get {
                return ResourceManager.GetString("Header_PageWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve your world now!.
        /// </summary>
        internal static string Header_Processing {
            get {
                return ResourceManager.GetString("Header_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 - server error.
        /// </summary>
        internal static string Header_ServerError {
            get {
                return ResourceManager.GetString("Header_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Info.
        /// </summary>
        internal static string Header_SessionInfo {
            get {
                return ResourceManager.GetString("Header_SessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in.
        /// </summary>
        internal static string Header_SignIn {
            get {
                return ResourceManager.GetString("Header_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Header_SignUp {
            get {
                return ResourceManager.GetString("Header_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve read and accept to the &lt;abbr title=&quot;Can be found in About page&quot;&gt;terms&lt;/abbr&gt;.
        /// </summary>
        internal static string Label_AcceptTerms {
            get {
                return ResourceManager.GetString("Label_AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Date.
        /// </summary>
        internal static string Label_ChangedDate {
            get {
                return ResourceManager.GetString("Label_ChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string Label_CreatedDate {
            get {
                return ResourceManager.GetString("Label_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Label_Data {
            get {
                return ResourceManager.GetString("Label_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data range.
        /// </summary>
        internal static string Label_DataRange {
            get {
                return ResourceManager.GetString("Label_DataRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Label_Duration {
            get {
                return ResourceManager.GetString("Label_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string Label_Guid {
            get {
                return ResourceManager.GetString("Label_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSDstr.
        /// </summary>
        internal static string Label_Project {
            get {
                return ResourceManager.GetString("Label_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Label_Results {
            get {
                return ResourceManager.GetString("Label_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Label_State {
            get {
                return ResourceManager.GetString("Label_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Label_StateCompleted {
            get {
                return ResourceManager.GetString("Label_StateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Message.
        /// </summary>
        internal static string Label_StateMessage {
            get {
                return ResourceManager.GetString("Label_StateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Label_StateStarted {
            get {
                return ResourceManager.GetString("Label_StateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Label_StateStopped {
            get {
                return ResourceManager.GetString("Label_StateStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving results....
        /// </summary>
        internal static string Label_WaitingCompleteSession {
            get {
                return ResourceManager.GetString("Label_WaitingCompleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication....
        /// </summary>
        internal static string Label_WaitingSignIn {
            get {
                return ResourceManager.GetString("Label_WaitingSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration....
        /// </summary>
        internal static string Label_WaitingSignUp {
            get {
                return ResourceManager.GetString("Label_WaitingSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session starting....
        /// </summary>
        internal static string Label_WaitingStartSession {
            get {
                return ResourceManager.GetString("Label_WaitingStartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session cancelling....
        /// </summary>
        internal static string Label_WaitingStopSession {
            get {
                return ResourceManager.GetString("Label_WaitingStopSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Link_About {
            get {
                return ResourceManager.GetString("Link_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it ».
        /// </summary>
        internal static string Link_AboutReadMore {
            get {
                return ResourceManager.GetString("Link_AboutReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Link_Home {
            get {
                return ResourceManager.GetString("Link_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more ».
        /// </summary>
        internal static string Link_HomeReadMore {
            get {
                return ResourceManager.GetString("Link_HomeReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Link_Login {
            get {
                return ResourceManager.GetString("Link_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Link_Logout {
            get {
                return ResourceManager.GetString("Link_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Link_Processing {
            get {
                return ResourceManager.GetString("Link_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Link_Results {
            get {
                return ResourceManager.GetString("Link_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was cancelled successfully. Calculation was stopped..
        /// </summary>
        internal static string Success_CancelSession {
            get {
                return ResourceManager.GetString("Success_CancelSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was completed successfully. Starting another....
        /// </summary>
        internal static string Success_CompleteSession {
            get {
                return ResourceManager.GetString("Success_CompleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was created successfully. Calculation is running....
        /// </summary>
        internal static string Success_CreateSession {
            get {
                return ResourceManager.GetString("Success_CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull ping.
        /// </summary>
        internal static string Success_PingSession {
            get {
                return ResourceManager.GetString("Success_PingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success authorization.
        /// </summary>
        internal static string Success_SignIn {
            get {
                return ResourceManager.GetString("Success_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success anonym authorization.
        /// </summary>
        internal static string Success_SignInAnonym {
            get {
                return ResourceManager.GetString("Success_SignInAnonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully registered. Please check your email..
        /// </summary>
        internal static string Success_SignUp {
            get {
                return ResourceManager.GetString("Success_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About jsDSTR - Javascript Distributed System for clasterization.
        /// </summary>
        internal static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site error.
        /// </summary>
        internal static string Title_GeneralError {
            get {
                return ResourceManager.GetString("Title_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jsDSTR - Javascript Distributed System for clasterization.
        /// </summary>
        internal static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Title_Login {
            get {
                return ResourceManager.GetString("Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - not found.
        /// </summary>
        internal static string Title_PageWasNotFound {
            get {
                return ResourceManager.GetString("Title_PageWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Title_Processing {
            get {
                return ResourceManager.GetString("Title_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of clasterization.
        /// </summary>
        internal static string Title_Results {
            get {
                return ResourceManager.GetString("Title_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 - server error.
        /// </summary>
        internal static string Title_ServerError {
            get {
                return ResourceManager.GetString("Title_ServerError", resourceCulture);
            }
        }
    }
}
