(function () {
    Date.prototype.format = function (format) //author: meizz
    {
        var o = {
            "M+": this.getMonth() + 1, //month
            "d+": this.getDate(),    //day
            "h+": this.getHours(),   //hour
            "m+": this.getMinutes(), //minute
            "s+": this.getSeconds(), //second
            "q+": Math.floor((this.getMonth() + 3) / 3),  //quarter
            "S": this.getMilliseconds() //millisecond
        };

        if (/(y+)/.test(format))
            format = format.replace(RegExp.$1,
                (this.getFullYear() + "").substr(4 - RegExp.$1.length));
        for (var k in o)
            if (new RegExp("(" + k + ")").test(format))
                format = format.replace(RegExp.$1,
                    RegExp.$1.length == 1 ? o[k] :
                        ("00" + o[k]).substr(("" + o[k]).length));
        return format;
    };

    var helpers = {
        returnUrlParameter: "ReturnUrl",
        defaultReturnUrl: "/",
        pwdMinLength: 5,

        getUrlParameterByName: function (name) {
            name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
            var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
                results = regex.exec(location.search);
            return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
        },

        returnBack: function () {
            var returnUrl = helpers.getUrlParameterByName(helpers.returnUrlParameter);
            if (returnUrl != "")
                window.location = returnUrl;
            else
                window.location = helpers.defaultReturnUrl;
        },

        parseDate: function (jsonDate) {
            return new Date(parseInt(jsonDate.substr(6)));
        },

        clearFromSomeeGeneratedScript: function (source) {
            var generatedСomment = "SCRIPT GENERATED BY SERVER! PLEASE REMOVE";
            if (source instanceof jQuery) {
                var generatedComments = source.contents().filter(function () {
                    return this.nodeType == 8 && this.textContent == generatedСomment;
                });
                if (generatedComments.length == 2)
                    $(generatedComments[0]).nextUntil(generatedComments[0]).remove();
                generatedComments.each(function () { $(this).remove(); });
            }
            else if (typeof source == "string") {
                generatedСomment = "<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->";
                var generatedCommentIndex = source.indexOf(generatedСomment);
                if (generatedCommentIndex != -1)
                    source = source.slice(0, generatedCommentIndex);
                return source;
            }
            return source;
        },

        saveToStorage: function(key, value) {
            if (key == null)
                return null;
            if (typeof(Storage) === "undefined")
                return null;
            localStorage[key] = value;
            return value;
        },

        getFromStorage: function (key) {
            if (key == null)
                return null;
            if (typeof (Storage) === "undefined")
                return null;
            return localStorage[key];
        }
    };

    var validation = {
        isEmail: function (email) {
            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            return regex.test(email);
        }
    };

    var ui = {
        errorClass: 'has-error',
        dateTimeFormat: "dd.MM.yyyy hh:mm:ss",

        addError: function (source, msg) {
            if (source != '')
                source += '</br>';
            return source + msg;
        },

        setAlertState: function ($alert, msg, cssClass) {
            if ($alert != null && msg != '') {
                var classToAdd = 'alert';
                if (typeof cssClass == "string") {
                    classToAdd += ' ' + cssClass;
                }
                else if (typeof cssClass == "boolean" && cssClass) {
                    classToAdd += ' alert-success';
                } else if (typeof cssClass == "boolean") {
                    classToAdd += ' alert-danger';
                }
                $alert.attr('class', '').addClass(classToAdd);
                $alert.html(msg);
                $alert.removeClass('hide');
            }
        },

        setButtonState: function ($btn, cssClass, title, state, dataState) {
            if ($btn != null) {
                if (state != null) {
                    $btn.button(state);
                    if (state == 'reset')
                        $btn.removeAttr('disabled');
                }
                if (cssClass != null)
                    $btn.attr('class', '').addClass('btn').addClass(cssClass);
                if (title != null)
                    $btn.html(title);
                if (dataState != null)
                    $btn.data('state', dataState);
            }
        }
    };

    var resources = {};

    var Processing = function () {
        var handlers = {
            beforeCreateSession: $.Callbacks(),
            beforeCancelSession: $.Callbacks(),

            failMaxAttemptsCreateSession: $.Callbacks(),
            failMaxAttemptsPingSession: $.Callbacks(),
            failMaxAttemptsCalculationSession: $.Callbacks(),

            successCreateSession: $.Callbacks(),
            failCreateSession: $.Callbacks(),

            successPingSession: $.Callbacks(),
            failPingSession: $.Callbacks(),

            successCancelSession: $.Callbacks(),
            failCancelSession: $.Callbacks(),

            successCompleteSession: $.Callbacks(),
            failCompleteSession: $.Callbacks(),

            failSessionClientNull: $.Callbacks(),
            failSessionServerNull: $.Callbacks(),
            failSessionInvalidState: $.Callbacks(),

            failSessionCalculation: $.Callbacks(),

            failCalculationNull: $.Callbacks(),
            failCalculationCompleted: $.Callbacks(),
            failCalculationFailed: $.Callbacks(),
            failCalculationError: $.Callbacks(),
            failCalculationBusy: $.Callbacks(),
            failCalculationInvalid: $.Callbacks(),

            successTask: $.Callbacks()
        };

        var currentSession;

        var checkCurrentSession = function (disableHandler) {
            if (!$.isPlainObject(currentSession)) {
                if(!disableHandler)
                    handlers.failSessionClientNull.fire();
                return false;
            }
            return true;
        };

        var checkSession = function (session, stateShouldBe, taskType, disableHandler) {
            if (!$.isPlainObject(session)) {
                if (!disableHandler)
                    handlers.failSessionServerNull.fire();
                return false;
            }
            else if (taskType != null && !checkCalculationTask(session, taskType)) {
                return false;
            }
            else if (stateShouldBe != null && session.State != stateShouldBe) {
                if (!disableHandler)
                    handlers.failSessionInvalidState.fire(session);
                return false;
            }
            return true;
        };

        var worker;

        var maxSessionAttempts = 5;
        var createSessionAttempts = 0;
        var pingSessionAttempts = 0;
        var calculationSessionAttempts = 0;
        var cancelCreateSession = false;

        var checkCreateSessionMaxAttempts = function () {
            if (createSessionAttempts >= maxSessionAttempts) {
                handlers.failMaxAttemptsCreateSession.fire(maxSessionAttempts);
                createSessionAttempts = 0;
                return false;
            }
            return true;
        };

        var checkPingSessionMaxAttempts = function () {
            if (pingSessionAttempts >= maxSessionAttempts) {
                timerStarted = false;
                if (worker != null)
                    worker.close();
                handlers.failMaxAttemptsPingSession.fire(maxSessionAttempts);
                pingSessionAttempts = 0;
                return false;
            }
            return true;
        };

        var checkCalculateSessionMaxAttempts = function () {
            if (calculationSessionAttempts >= maxSessionAttempts) {
                if (worker != null)
                    worker.close();
                handlers.failMaxAttemptsCalculationSession.fire(maxSessionAttempts);
                calculationSessionAttempts = 0;
                return false;
            }
            return true;
        };

        var checkCalculationTask = function (session, taskType) {
            if (!$.isPlainObject(session.CalculationTask)) {
                handlers.failCalculationNull.fire(session);
                return false;
            }
            var task = session.CalculationTask;
            switch (task.State) {
                case Processing.calculationState.Started:
                    handlers.failCalculationError.fire(session);
                    return false;
                case Processing.calculationState.AssignmentLoop:
                    if (taskType == sessionTaskType.get) {
                        return true;
                    }
                    handlers.failCalculationError.fire(session);
                    return false;
                case Processing.calculationState.UpdateCentroidsLoop:
                    if (taskType == sessionTaskType.get) {
                        return true;
                    }
                    handlers.failCalculationError.fire(session);
                    return false;
                case Processing.calculationState.Completed:
                    if (taskType == sessionTaskType.get) {
                        cancelCreateSession = true;
                    }
                    handlers.failCalculationCompleted.fire(session);
                case Processing.calculationState.Failed:
                    if (taskType == sessionTaskType.get) {
                        cancelCreateSession = true;
                    }
                    handlers.failCalculationFailed.fire(session);
                    return false;
                case Processing.calculationState.Successful:
                    if (taskType == sessionTaskType.get) {
                        handlers.failCalculationError.fire(session);
                        return false;
                    }
                    return true;
                case Processing.calculationState.Error:
                    handlers.failCalculationError.fire(session);
                    return false;
                case Processing.calculationState.Busy:
                    if (taskType == sessionTaskType.get) {
                        handlers.failCalculationBusy.fire(session);
                    } else {
                        handlers.failCalculationError.fire(session);
                    }
                    return false;
                default:
                    handlers.failCalculationError.fire(session);
                    return false;
            }
        };

        var vectorsStoreKey = "jsdKmeansVectors";

        var Kmeans = function (task) {
            if (!$.isPlainObject(task))
                throw "Kmeans: task is null";
            if (task.State != Processing.calculationState.AssignmentLoop && task.State != Processing.calculationState.UpdateCentroidsLoop)
                throw "Kmeans: invalid task state";
            if (task.VectorsCached) {
                var vectorsJson = helpers.getFromStorage(vectorsStoreKey);
                if (vectorsJson != null) {
                    task.Vectors = JSON.parse(vectorsJson);
                } else {
                    task.VectorsCached = false;
                    throw "Kmeans: no vectors in cache";
                }
            } else if (task.Vectors == null) {
                throw "Kmeans: vectors is null";
            } else {
                if(helpers.saveToStorage(vectorsStoreKey, JSON.stringify(task.Vectors)) != null)
                    task.VectorsCached = true;
            }
            if (Number(task.SlotStart) == NaN || task.SlotStart < 0)
                throw "Kmeans: slotstart is invalid";
            if (Number(task.SlotCapacity) == NaN || task.SlotCapacity <= 0)
                throw "Kmeans: slotcapacity is invalid";
            if (Number(task.K) == NaN || task.K <= 0 || task.K > task.Vectors.length)
                throw "Kmeans: k is invalid";

            if (task.State == Processing.calculationState.AssignmentLoop) {
                if (task.Centroids == null || task.Centroids.length != task.K)
                    throw "Kmeans: centroids is invalid";
                this.execute = function (d) {
                    function euclidianDistance(a, b) { // correct distance for coordinates
                        var ds = (a.V1 - b.V1) * (a.V1 - b.V1) +
                            (a.V1 - b.V2) * (a.V1 - b.V2) +
                            (a.V1 - b.V3) * (a.V1 - b.V3);
                        ds = Math.sqrt(ds);
                        return ds;
                    };

                    var n = d.vectors.length;
                    var assignments = new Array(n);
                    for (var i = 0; i < n; i++) {
                        var vector = d.vectors[i];
                        var mindist = Number.MAX_VALUE;
                        var best = 0;
                        for (var j = 0; j < d.k; j++) {
                            var dist = euclidianDistance(d.centroids[j], vector);
                            if (dist < mindist) {
                                mindist = dist;
                                best = j;
                            }
                        }
                        assignments[i] = {
                            С: best,
                            V: i
                        };
                    }
                    return assignments;
                };
                this.handleResults = function (d) {
                    task.Vectors = null;
                    task.Centroids = null;
                    task.Assignments = d;
                };
            }
            else if (task.State == Processing.calculationState.UpdateCentroidsLoop) {
                if (task.Centroids == null || task.Centroids.length != task.K)
                    throw "Kmeans: centroids is invalid";
                if (task.Assignments == null)
                    throw "Kmeans: assignments is invalid";
                this.execute = function (d) {
                    function addVectors(a, b) {
                        return {
                            Id: a.Id,
                            V1: a.V1 + b.V1,
                            V2: a.V2 + b.V2,
                            V3: a.V3 + b.V3
                        };
                    };
                    var n = d.vectors.length;
                    var centroids = new Array(d.k);
                    for (var i = 0; i < n; i++) {
                        var cluster = d.assignments[i];
                        if (centroids[cluster] == null)
                            centroids[cluster] = d.vectors[i];
                        else
                            centroids[cluster] = addVectors(centroids[cluster], d.vectors[i]);
                    }
                    return centroids;
                };
                this.handleResults = function (d) {
                    task.Vectors = null;
                    task.Centroids = d;
                    task.Assignments = null;
                };
            }

            this.getData = function () {
                return {
                    vectors: task.Vectors.slice(task.SlotStart, task.SlotStart + task.SlotCapacity),
                    centroids: task.Centroids,
                    assignments: task.Assignments,
                    k: task.K
                };
            };

            this.task = task;
        };

        var sessionTaskType = {
            get: 1,
            complete: 2,
            cancel: 3
        };

        var cloneSessionWithoutTask = function (session) {
            if (!$.isPlainObject(session))
                return session;
            var clone = {
                CreatedDate: session.CreatedDate,
                ChangedDate: session.ChangedDate,
                Guid: session.Guid,
                UserName: session.UserName,
                State: session.State,
                StateMessage: session.StateMessage,
                CalculationId: session.CalculationId,
                CalculationTask: session.CalculationTask != null ? {
                    SessionGuid: session.CalculationTask.SessionGuid,
                    State: session.CalculationTask.State,
                    StateMessage: session.CalculationTask.StateMessage,
                    VectorsCached: session.CalculationTask.VectorsCached
                } : {
                    VectorsCached: helpers.getFromStorage(vectorsStoreKey) != null
                }
            };
            return clone;
        };

        var createSession = function () {
            if (worker != null)
                worker.close();
            timerStarted = false;
            if (cancelCreateSession) {
                cancelCreateSession = false;
                return;
            }
            if (!checkCreateSessionMaxAttempts() || !checkPingSessionMaxAttempts() || !checkCalculateSessionMaxAttempts())
                return;
            handlers.beforeCreateSession.fire();
            createSessionAttempts++;
            requestExecuted = true;
            var sessionClone;
            if (currentSession == null) {
                sessionClone = {
                    CalculationTask: {
                        VectorsCached: helpers.getFromStorage(vectorsStoreKey) != null
                    }
                };
            } else {
                sessionClone = cloneSessionWithoutTask(currentSession);
            }
            
            $.post('/processing/createsession?sessionjson=' + JSON.stringify(sessionClone), function (session) {
                if (checkSession(session, Processing.sessionState.Started, sessionTaskType.get)) {
                    try {
                        var kmeans = new Kmeans(session.CalculationTask);
                    } catch (ex) {
                        handlers.failCalculationInvalid.fire(ex, session);
                        createSession();
                        return;
                    }
                    worker = cw(kmeans.execute);
                    worker.data(kmeans.getData()).then(function (d) {
                        if (checkCurrentSession()) {
                            kmeans.handleResults(d);
                            calculationSessionAttempts = 0;
                            completeSession();
                        } else {
                            createSession();
                        }
                    }, function (d) {
                        if (d != "closed") {
                            calculationSessionAttempts++;
                            handlers.failSessionCalculation.fire(d);
                            createSession();
                        }
                    });
                    currentSession = session;
                    handlers.successCreateSession.fire(session);
                    createSessionAttempts = 0;
                    requestExecuted = false;

                    timerStarted = true;
                    startPing();
                } else {
                    createSession();
                }
            }).fail(function (d) {
                handlers.failCreateSession.fire(d.statusText);
                createSession();
                requestExecuted = false;
            });
        };

        var pingSession = function () {
            if (!requestExecuted) {
                if (!checkPingSessionMaxAttempts())
                    return;
                pingSessionAttempts++;
                if (checkCurrentSession()) {
                    requestExecuted = true;
                    var sessionClone = cloneSessionWithoutTask(currentSession);
                    $.post('/processing/pingsession?sessionjson=' + JSON.stringify(sessionClone), function (session) {
                        if (checkCurrentSession(true) && checkSession(session, currentSession.State, null, true)) {
                            pingSessionAttempts = 0;
                            currentSession = session;
                            handlers.successPingSession.fire(session);
                        } else {
                            //createSession();
                        }
                        requestExecuted = false;
                    }).fail(function (d) {
                        handlers.failPingSession.fire(d.statusText);
                        requestExecuted = false;
                    });
                } else {
                    createSession();
                }
            }
        };

        var completeSession = function () {
            timerStarted = true;
            if (checkCurrentSession()) {
                requestExecuted = true;
                $.post('/processing/completesession?sessionjson=' + JSON.stringify(currentSession), function (session) {
                    requestExecuted = false;
                    if (checkCurrentSession() && checkSession(session, Processing.sessionState.Completed, sessionTaskType.complete)) {
                        currentSession = session;
                        handlers.successCompleteSession.fire(session);
                    }
                    requestExecuted = false;
                    createSession();
                }).fail(function (d) {
                    handlers.failCompleteSession.fire(d.statusText);
                    requestExecuted = false;
                    createSession();
                });
            } else {
                createSession();
            }
        };

        var cancelSession = function () {
            handlers.beforeCancelSession.fire();
            timerStarted = false;
            if (worker != null)
                worker.close();
            if (checkCurrentSession()) {
                requestExecuted = true;
                var sessionClone = cloneSessionWithoutTask(currentSession);
                $.post('/processing/cancelsession?sessionjson=' + JSON.stringify(sessionClone), function (session) {
                    requestExecuted = false;
                    if (checkCurrentSession() && checkSession(session, Processing.sessionState.Stopped, sessionTaskType.cancel)) {
                        currentSession = session;
                        handlers.successCancelSession.fire(session);
                    }
                }).fail(function (d) {
                    handlers.failCancelSession.fire(d.statusText);
                    requestExecuted = false;
                });
            }
        };

        var timerStarted = false;
        var requestExecuted = false;
        var timerInterval = 500;

        var startPing = function () {
            if (timerStarted) {
                pingSession();
                setTimeout(startPing, timerInterval);
            }
        };

        this.startProcessing = createSession;
        this.stopProcessing = cancelSession;
        this.handlers = handlers;
        this.currentSession = currentSession;

    };
    Processing.sessionState = {
        Started: 1,
        Stopped: 2,
        Completed: 3
    };
    Processing.calculationState = {
        Started: 1,
        AssignmentLoop: 2,
        UpdateCentroidsLoop: 3,
        Completed: 4,
        Failed: 5,

        Successful: 6,
        Error: 7,
        Busy: 8
    };

    var account = {
        signIn: function (email, pwd, remember, success, fail) {
            $.post('/account/signin?email=' + email + '&pwd=' + pwd + '&remember=' + remember, success).fail(fail);
        },
        signInAnonym: function (success, fail) {
            $.post('/account/signinanonym', success).fail(fail);
        },
        signUp: function (email, pwd, success, fail) {
            $.post('/account/signup?email=' + email + '&pwd=' + pwd, success).fail(fail);
        }
    };

    var ready = function () {
        (function init() {
            helpers.clearFromSomeeGeneratedScript($('body'));
        })();

        $('#btnSignIn').click(function () {
            var error = '';
            var $email = $('#txtSignInEmail');
            var email = $email.val();
            var $pwd = $('#txtSignInPwd');
            var pwd = $pwd.val();
            var $remember = $('#chkRemember');
            var remember = $remember.prop('checked') == true;
            var $alert = $("#msgSignIn");
            var $btn = $(this);

            if (email == '' || !validation.isEmail(email)) {
                error = ui.addError(error, resources.Error_Email);
                $email.parent().addClass(ui.errorClass);
                $email.focus();
            } else
                $email.parent().removeClass(ui.errorClass);
            if (pwd == '' || pwd.length < helpers.pwdMinLength) {
                if (error == '')
                    $pwd.focus();
                error = ui.addError(error, resources.Error_Password);
                $pwd.parent().addClass(ui.errorClass);
            } else
                $pwd.parent().removeClass(ui.errorClass);
            if (error == '') {
                $btn.button('loading');
                $btn.attr('disabled', 'disabled');
                account.signIn(email, pwd, remember, function (d) {
                    $btn.button('reset');
                    d = helpers.clearFromSomeeGeneratedScript(d);
                    if (d == "True") {
                        ui.setAlertState($alert, resources.Success_SignIn, true);
                        setTimeout(helpers.returnBack, ui.messageDelay);
                    } else {
                        ui.setAlertState($alert, resources.Error_SignIn, false);
                        $email.focus();
                        $btn.removeAttr('disabled');
                    }
                }, function () {
                    $btn.button('reset');
                    ui.setAlertState($alert, resources.Error_General, false);
                });
            } else
                ui.setAlertState($alert, error, false);
            return false;
        });

        $('#btnSignUp').click(function () {
            var error = '';
            var $email = $('#txtSignUpEmail');
            var email = $email.val();
            var $pwd = $('#txtSignUpPwd');
            var pwd = $pwd.val();
            var $accept = $('#chkAccept');
            var accept = $accept.prop('checked') == true;
            var $alert = $("#msgSignUp");
            var $btn = $(this);

            if (email == '' || !validation.isEmail(email)) {
                error = ui.addError(error, resources.Error_Email);
                $email.parent().addClass(ui.errorClass);
                $email.focus();
            } else
                $email.parent().removeClass(ui.errorClass);
            if (pwd == '' || pwd.length < helpers.pwdMinLength) {
                if (error == '')
                    $pwd.focus();
                error = ui.addError(error, resources.Error_Password);
                $pwd.parent().addClass(ui.errorClass);
            } else
                $pwd.parent().removeClass(ui.errorClass);
            if (!accept) {
                error = ui.addError(error, resources.Error_NotAcceptedTerms);
            }
            if (error == '') {
                $btn.button('loading');
                $btn.attr('disabled', 'disabled');
                account.signUp(email, pwd, function (d) {
                    $btn.button('reset');
                    d = helpers.clearFromSomeeGeneratedScript(d);
                    if (d == "") {
                        ui.setAlertState($alert, resources.Success_SignUp, true);
                        setTimeout(helpers.returnBack, ui.messageDelay);
                    } else {
                        ui.setAlertState($alert, d, false);
                        $email.focus();
                        $btn.removeAttr('disabled');
                    }
                }, function () {
                    $btn.button('reset');
                    ui.setAlertState($alert, resources.Error_General, false);
                });
            } else
                ui.setAlertState($alert, error, false);
            return false;
        });

        $('#btnSignInAnonym').click(function () {
            var $alert = $("#msgSignInAnonym");
            var $btn = $(this);
            $btn.button('loading');
            $btn.attr('disabled', 'disabled');
            account.signInAnonym(function (d) {
                $btn.button('reset');
                d = helpers.clearFromSomeeGeneratedScript(d);
                if (d == 'True') {
                    ui.setAlertState($alert, resources.Success_SignInAnonym, true);
                    setTimeout(helpers.returnBack, ui.messageDelay);
                } else {
                    ui.setAlertState($alert, resources.Error_SignInAnonym, false);
                    $btn.removeAttr('disabled');
                }
            }, function () {
                $btn.button('reset');
                ui.setAlertState($alert, resources.Error_General, false);
            });
            return false;
        });

        var createProcessing = function () {
            var $btn = $('#btnProcessing');
            var $alert = $('#msgProcessing');
            var processing = new Processing();
            processing.handlers.beforeCreateSession.add(function () {
                $btn.button('starting');
                setTimeout(function () {
                    $btn.attr('disabled', 'disabled');
                }, 0);
            });
            processing.handlers.beforeCancelSession.add(function () {
                $btn.button('stopping');
                setTimeout(function () {
                    $btn.attr('disabled', 'disabled');
                }, 0);
            });

            processing.handlers.failMaxAttemptsCreateSession.add(function (maxAttempts) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_MaxAttemptsCreateSession, "alert-danger");
                updateProcessingInfo(null, false);
                console.log("Fail max attempts create session: " + maxAttempts);
            });
            processing.handlers.failMaxAttemptsPingSession.add(function (maxAttempts) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_MaxAttemptsPingSession, "alert-danger");
                updateProcessingInfo(null, false);
                console.log("Fail max attempts ping session: " + maxAttempts);
            });
            processing.handlers.failMaxAttemptsCalculationSession.add(function (maxAttempts) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_MaxAttemptsCalculateSession, "alert-danger");
                updateProcessingInfo(null, false);
                console.log("Fail max attempts calculate session: " + maxAttempts);
            });

            processing.handlers.successCreateSession.add(function (session) {
                ui.setButtonState($btn, 'btn-danger', resources.Button_StopSession, 'reset', 'stop');
                ui.setAlertState($alert, resources.Success_CreateSession, "alert-success");
                updateProcessingInfo(session, true);
                console.log('Success create session: ' + JSON.stringify(session));
            });
            processing.handlers.failCreateSession.add(function (data) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CreateSession, false);
                updateProcessingInfo(null, false);
                console.log('Fail create session: ' + JSON.stringify(data));
            });

            processing.handlers.successPingSession.add(function (session) {
                if (session.state != Processing.sessionState)
                    updateProcessingInfo(session, true);
                console.log('Success ping session: ' + JSON.stringify(session));
            });
            processing.handlers.failPingSession.add(function (data) {
                console.log('Fail ping session: ' + JSON.stringify(data));
            });

            processing.handlers.successCancelSession.add(function (session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Success_CancelSession, 'alert-warning');
                updateProcessingInfo(session, true);
                console.log('Success cancel session: ' + JSON.stringify(session));
            });
            processing.handlers.failCancelSession.add(function (data) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CancelSession, false);
                updateProcessingInfo(null, false);
                console.log('Fail cancel session: ' + JSON.stringify(data));
            });

            processing.handlers.successCompleteSession.add(function (session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Success_CompleteSession, true);
                updateProcessingInfo(session, true);
                console.log('Success complete session: ' + JSON.stringify(session));
            });
            processing.handlers.failCompleteSession.add(function (data) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CompleteSession, false);
                updateProcessingInfo(null, false);
                console.log('Fail complete session: ' + JSON.stringify(data));
            });

            processing.handlers.failSessionClientNull.add(function () {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_SessionClientNull, false);
                updateProcessingInfo(null, false);
                console.log('Fail session client null');
            });
            processing.handlers.failSessionServerNull.add(function () {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_SessionServerNull, false);
                updateProcessingInfo(null, false);
                console.log('Fail session server null');
            });
            processing.handlers.failSessionInvalidState.add(function (session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_SessionInvalidState, false);
                updateProcessingInfo(null, false);
                console.log('Fail session invalid state: ' + JSON.stringify(session));
            });
            processing.handlers.failSessionCalculation.add(function (error) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_SessionCalculation, false);
                updateProcessingInfo(null, false);
                console.log('Fail session calculation: ' + error);
            });

            processing.handlers.failCalculationBusy.add(function (session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CalculationBusy, false);
                updateProcessingInfo(null, false);
                console.log('Fail calculation busy: ' + JSON.stringify(session));
            });
            processing.handlers.failCalculationCompleted.add(function (session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CalculationCompleted, 'alert-warning');
                updateProcessingInfo(null, false);
                console.log('Fail calculation completed: ' + JSON.stringify(session));
            });
            processing.handlers.failCalculationError.add(function (session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CalculationError, false);
                updateProcessingInfo(null, false);
                console.log('Fail calculation error: ' + JSON.stringify(session));
            });
            processing.handlers.failCalculationFailed.add(function (session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CalculationFailed, false);
                updateProcessingInfo(null, false);
                console.log('Fail calculation failed: ' + JSON.stringify(session));
            });
            processing.handlers.failCalculationInvalid.add(function (ex, session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CalculationInvalid, false);
                updateProcessingInfo(null, false);
                console.log('Fail calculation invalid: ' + ex + '; session: ' + JSON.stringify(session));
            });
            processing.handlers.failCalculationNull.add(function (session) {
                ui.setButtonState($btn, 'btn-success', resources.Button_StartSession, 'reset', 'start');
                ui.setAlertState($alert, resources.Error_CalculationNull, false);
                updateProcessingInfo(null, false);
                console.log('Fail calculation null: ' + JSON.stringify(session));
            });

            return processing;
        };

        var updateProcessingInfo = function (session, show) {
            var $sessionInfo = $('#msgProcessingInfo');
            if (show && $.isPlainObject(session)) {
                var $createdDate = $('#lblCreatedDate');
                var $changedDate = $('#lblChangedDate');
                var $guid = $('#lblGuid');
                var $userName = $('#lblUserName');
                var $state = $('#lblState');
                var $stateMessage = $('#lblStateMessage');
                var $data = $('#lblData');

                $createdDate.html(helpers.parseDate(session.CreatedDate).format(ui.dateTimeFormat));
                $changedDate.html(helpers.parseDate(session.ChangedDate).format(ui.dateTimeFormat));
                $guid.html(session.Guid);
                $userName.html(session.UserName);
                var state = "";
                switch (session.State) {
                    case Processing.sessionState.Started:
                        state = resources.Label_StateStarted;
                        break;
                    case Processing.sessionState.Stopped:
                        state = resources.Label_StateStopped;
                        break;
                    case Processing.sessionState.Completed:
                        state = resources.Label_StateCompleted;
                        break;
                }
                $state.html(state);
                $stateMessage.html(session.StateMessage);
                if (session.Results != null) {
                    $data.html(session.Results).parent().removeClass('hide');
                } else {
                    $data.parent().addClass('hide');
                }

                $sessionInfo.removeClass('hide');
            } else {
                $sessionInfo.addClass('hide');
            }
        };

        var currentProcessing;

        $('#btnProcessing').click(function () {
            if (currentProcessing == null)
                currentProcessing = createProcessing();
            var $btn = $(this);
            var state = $btn.data('state');
            if (state == null) {
                state = 'start';
                $btn.data('state', state);
            }
            if (state == 'start') {
                currentProcessing.startProcessing();
            }
            else if (state == 'stop') {
                currentProcessing.stopProcessing();
            }
        });
    };

    window.JSD = function () {
        this.helpers = helpers;
        this.validation = validation;
        this.Processing = Processing;
        this.resources = resources;

        $(document).ready(ready);
    };

    window.jsd = new JSD();
})();